### ISSUE TITLE
Supporting a Panel View having an easy reference to its controller

### ISSUE THREAD

**Issue by Esildor** [coryleach/UnityGUI#9]
When using this library, I often need a PanelView to reference its controller.

For example, when a button is pressed, the panel view might need to go to its controller to alter some game state. With the current implementation, it's a bit cumbersome to get access to a panels controller:

`public class SomeCoolPanelView : AnimatedPanelView
  {
    public PanelViewControllerProvider Provider;
    public PanelType SomeCoolPanelView;

    private SomeCoolPanelViewController controller;

    private void OnEnable()
    {
      controller = Provider.GetOrCreate(SomeCoolPanelView) as SomeCoolPanelViewController;
    }

    public void PressedSomething() => controller.OnPressedSomething();
  }`

Would be interested to see if there was a way that PanelViewBase could somehow contain an instance of its corresponding controller? Been thinking about trying to implement it myself but wanted to get some thoughts.

**Comment by coryleach** [comment]
My preferred way of doing what is in your example is to expose an event on the view that the controller can subscribe to when a view is loaded or shown and maintain a one way dependency from controller to view rather than create the tight coupling between the two.

If you want to create a pattern where the view always has a reference to its controller I think the ideal thing to do would be to  assign the controller reference to the view in the ViewDidLoad method of the PanelViewController class.

**Comment by Esildor** [comment]
Great points! After some thought, it does feel a lot cleaner to expose events on the view that the controller can sub too!
